# Deployment de Rust
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-api
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rust-api
        image: 34.139.16.44.nip.io/sopes/rust-api:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "20m"
            memory: "5Mi"
          limits:
            cpu: "50m"
            memory: "100Mi"
---

# Service para Rust
apiVersion: v1
kind: Service
metadata:
  name: rust-api-service
  namespace: proyecto2
spec:
  selector:
    app: rust-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---

# Ingress para Rust
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rust-api-ingress
  namespace: proyecto2
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: 
spec:
  rules:
  - host: ""
    http:
      paths:
      - path: /input
        pathType: Prefix
        backend:
          service:
            name: rust-api-service
            port:
              number: 80
---

# HPA para Rust
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rust-api-hpa
  namespace: proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
