# RabbitMQWritter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitwritter
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitwritter
  template:
    metadata:
      labels:
        app: rabbitwritter
    spec:
      containers:
      - name: rabbitwritter
        image: 34.139.16.44.nip.io/sopes/rabbitwritter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6000

---
# KafkaWritter
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafkawritter
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafkawritter
  template:
    metadata:
      labels:
        app: kafkawritter
    spec:
      containers:
      - name: kafkawritter
        image: 34.139.16.44.nip.io/sopes/kafkawritter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6000

---
# Service para RabbitMQWritter
apiVersion: v1
kind: Service
metadata:
  name: rabbitwritter
  namespace: proyecto2
spec:
  selector:
    app: rabbitwritter
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP

---
# Service para KafkaWritter
apiVersion: v1
kind: Service
metadata:
  name: kafkawritter
  namespace: proyecto2
spec:
  selector:
    app: kafkawritter
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
  type: ClusterIP
